version: '3.7'

services:
    server:
        build: ./server
        command: app.py run -h 0.0.0.0
        volumes:
          - ./server/:/usr/src/app/
        ports:
          - 5000:5000
        environment:
          - FLASK_ENV=development
          - FLASK_APP=app.py
          - FLASK_DEBUG=1     
    client:
        tty: true
        build: 
          context: ./client
          dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
        links:
            - server
