tools:
  exceptions: https://sentry.io/organizations/dcsil/issues/?project=5450618
  server-ci: https://github.com/dcsil/Custos/actions?query=workflow%3A%22Server+Continuous+Integration%22
  client-ci: https://github.com/dcsil/Custos/actions?query=workflow%3A%22Client+Continuous+Integration%22

services:
  production: https://... (link to the dashboard, not the running app)
  database: https://custos-ae3f4.firebaseio.com

docs:
  getting_started: ./README.md
  
commands:
  bootstrap: bash script/bootstrap
  server: docker-compose up server
  client: docker-compose up client
  test: bash script/run_all_tests
  
  
  
tools:
  logging: https://app.logdna.com/b1e9dedef0/logs/view

services:
  production: https://dashboard.heroku.com/apps/klucth-app