tools:
  logging: https://app.logdna.com/8472fab2bd/logs/view
  exceptions: https://sentry.io/organizations/dcsil/issues/?project=5450618
  ci:
    server: https://github.com/dcsil/Custos/actions?query=workflow%3A%22Server+Continuous+Integration%22
    client: https://github.com/dcsil/Custos/actions?query=workflow%3A%22Client+Continuous+Integration%22

services:
  production: https://custos-client.herokuapp.com/
  dashboard: https://dashboard.heroku.com/apps/custos-client
  server: https://custos-server.herokuapp.com/

docs:
  getting_started: ./README.md
  
commands:
  bootstrap: bash script/bootstrap
  server: docker-compose up server
  client: docker-compose up client
  database: https://custos-ae3f4.firebaseio.com
  test: bash script/run_all_tests
  
