#!/bin/bash
set -e

# install docker if not already installed
if [ -x "$(command -v docker)" ]; then
    docker info > /dev/null 2>&1
    # run docker-compose to bring up containers
    echo "Bringing up containers"
    echo "======================"
    echo "Building..."
    docker-compose build
    echo "Running..."
    docker-compose up -d
    echo " "
    echo "Client running on: http://localhost:3000/"
    echo "Server running on: http://localhost:5000/"
    echo "======================"
    echo "Run script/bring_down to terminate app."
    
else
    echo "You do not have Docker installed or running."
    while true; do
        read -p "Do you want to install Docker (y/n)" yn
        case $yn in
            [Yy]* ) curl -sSL https://get.docker.com/ | sh ; echo "Please re run script with Docker running"; exit 0;;
            [Nn]* ) echo "Please install Docker to run this app"; exit 1;;
            * ) echo "Please enter y/n";;
        esac
    done
fi


