name: Client Continuous Integration

on:
    pull_request:
      branches: [ master ]
    push:
      branches: [master]
  
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [12.x]
    
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install Dependencies
          working-directory: ./client
          run: npm ci
        - name: Build
          working-directory: ./client
          run: npm run build --if-present
        - name: Test Using Jest
          working-directory: ./client
          run: npm test -- --coverage
        - name: Generate Coverage Report
        #   working-directory: ./client
        #   run: npm test -- --coverage
        # - name: Upload to CodeCov
        #   uses: codecov/codecov-action@v1
        #   with:
        #     token: ${{ secrets.CODECOV_TOKEN }}
        #     name: codecov-umbrella
        #     fail_ci_if_error: true
        #     verbose: true
          uses: paambaati/codeclimate-action@v2.7.4
          env:
            CC_TEST_REPORTER_ID: 91efde6e162dce796b87e283aa98e2eaf529e26ef4e3a79a04f3a92e742faff6
          with:
            workingDirectory: client
            coverageCommand: npm test 
