name: Code Coverage Check

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate Coverage Report
      working-directory: ./server
      run: |
        pip install -r requirements.txt
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true