name: Code Coverage Check

on:
    pull_request:
      branches: [ master ]
    push:
      branches: [ master ]

jobs:
    coverage:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [12.x]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          working-directory: ./server
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pytest-cov
        - name: Set up Node ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          working-directory: ./client
          run: npm ci
        - name: Install Code Climate
          run: |
            mkdir tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
        - name: Generate Server Coverage
          working-directory: ./server
          run: |
            pytest --cov=./ --cov-report=xml
            ./../cc-test-reporter format-coverage -t coverage.py -o codeclimate.server.json
            mv codeclimate.server.json ../tmp
        - name: Generate Client Coverage
          working-directory: ./client
          run: |
            npm test -- --coverage --watchAll=false
            ./../cc-test-reporter format-coverage -t lcov -o codeclimate.client.json
            mv codeclimate.client.json ../tmp
        - name: Upload to Code Climate
          env:
            CC_TEST_REPORTER_ID: 91efde6e162dce796b87e283aa98e2eaf529e26ef4e3a79a04f3a92e742faff6
          run: |
            # ls
            ls tmp
            ./cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./cc-test-reporter upload-coverage -i tmp/codeclimate.total.json --id $CC_TEST_REPORTER_ID
