name: Deploy to Heroku

on:
  push:
    branches: [master]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "custos-client"
          heroku_email: "labibc01@gmail.com"
          appdir: "./client"
          healthcheck: "https://custos-client.herokuapp.com/"
        env:
          HD_CHECK: "true"

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "custos-server"
          heroku_email: "labibc01@gmail.com"
          appdir: "./server"
          healthcheck: "https://custos-server.herokuapp.com/"
        env:
          HD_CHECK: "true"
          
